name: Develop CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  validate:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install JS dependencies
        run: npm ci

      - name: Run ESLint
        continue-on-error: true
        run: npm run lint

      - name: Upload ESLint Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: eslint-report
          path: eslint-report.html

      - name: Run Unit Test
        continue-on-error: true
        run: npm run test

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-report
          path: html-report/

  build_android_develop:
    name: Build Android (Develop)
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Set up JDK Version 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Install JS dependencies
        run: npm ci

      - name: Create gradle.properties from Base64
        run: |
          echo "${{ secrets.GRADLE_PROPERTIES_BASE_64 }}" | base64 --decode > android/gradle.properties

      - name: Create .env.development from Base64
        run: |
          mkdir -p env
          echo "${{ secrets.ENV_DEV_BASE_64 }}" | base64 --decode > env/.env.development

      - name: Build Offnal Android (Develop Debug)
        run: cd android && ./gradlew assembleDevelopDebug

  build_ios_develop:
    name: Build iOS (Develop)
    needs: validate
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm

      - name: Set up Ruby (with cache)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'
          bundler-cache: true

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install JS dependencies
        run: npm ci

      - name: Create .env.development from Base64
        run: |
          mkdir -p env
          echo "${{ secrets.ENV_DEV_BASE_64 }}" | base64 --decode > env/.env.development
          cp env/.env.development .env

      - name: Install iOS dependencies (with CocoaPods)
        run: cd ios && bundle exec pod install

      - name: Build Offnal iOS (Development Debug)
        run: |
          cd ios
          xcodebuild -workspace Offnal.xcworkspace \
                     -scheme Development \
                     -sdk iphonesimulator \
                     -configuration Debug \
                     clean build
